// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: provenance/registry/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the registry module's parameters.
type Params struct {
	// role_authorizations are the default authorization policies that govern role updates for
	// registry entries that are not associated with a registry class. They form the middle tier of
	// the two-tier resolution: a registry class policy takes precedence, then these module defaults,
	// and finally roles without any policy fall back to legacy NFT-owner authorization.
	RoleAuthorizations []RoleAuthorization `protobuf:"bytes,1,rep,name=role_authorizations,json=roleAuthorizations,proto3" json:"role_authorizations"`
	// pending_change_expiry is how long a pending role change remains valid after it is proposed.
	// Approvals received after the expiry are rejected and the change is cleaned up.
	// Zero value (default) means pending changes never expire.
	PendingChangeExpiry time.Duration `protobuf:"bytes,2,opt,name=pending_change_expiry,json=pendingChangeExpiry,proto3,stdduration" json:"pending_change_expiry"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5f5edf5698b7c6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRoleAuthorizations() []RoleAuthorization {
	if m != nil {
		return m.RoleAuthorizations
	}
	return nil
}

func (m *Params) GetPendingChangeExpiry() time.Duration {
	if m != nil {
		return m.PendingChangeExpiry
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "provenance.registry.v1.Params")
}

func init() {
	proto.RegisterFile("provenance/registry/v1/params.proto", fileDescriptor_5e5f5edf5698b7c6)
}

var fileDescriptor_5e5f5edf5698b7c6 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4e, 0x2a, 0x31,
	0x14, 0x40, 0xa7, 0xef, 0x19, 0x62, 0x86, 0xdd, 0xa0, 0x06, 0x58, 0x14, 0xa2, 0x1b, 0x34, 0xb1,
	0x0d, 0xe8, 0x0f, 0x88, 0xba, 0x27, 0x6c, 0x4c, 0xdc, 0x60, 0x81, 0x5a, 0x1a, 0xa1, 0xb7, 0xe9,
	0x74, 0x08, 0xe3, 0x57, 0xb8, 0xf4, 0x7f, 0xdc, 0xb0, 0x64, 0xe9, 0x4a, 0xcd, 0xcc, 0x8f, 0x18,
	0xca, 0x90, 0x19, 0x8d, 0xec, 0x7a, 0x73, 0xcf, 0x3d, 0x39, 0xa9, 0x7f, 0xa2, 0x0d, 0xcc, 0xb9,
	0x62, 0x6a, 0xc4, 0xa9, 0xe1, 0x42, 0x86, 0xd6, 0xc4, 0x74, 0xde, 0xa6, 0x9a, 0x19, 0x36, 0x0b,
	0x89, 0x36, 0x60, 0x21, 0x38, 0xca, 0x21, 0xb2, 0x85, 0xc8, 0xbc, 0x5d, 0x3f, 0x10, 0x20, 0xc0,
	0x21, 0x74, 0xfd, 0xda, 0xd0, 0xf5, 0xb3, 0x1d, 0x4a, 0x16, 0xd9, 0x09, 0x18, 0xf9, 0xcc, 0xac,
	0x04, 0x95, 0xb1, 0x58, 0x00, 0x88, 0x29, 0xa7, 0x6e, 0x1a, 0x46, 0x8f, 0x74, 0x1c, 0x99, 0xc2,
	0xfe, 0xf8, 0x0d, 0xf9, 0xa5, 0x9e, 0x4b, 0x09, 0x1e, 0xfc, 0x8a, 0x81, 0x29, 0x1f, 0xfc, 0xd0,
	0x84, 0x55, 0xd4, 0xfc, 0xdf, 0x2a, 0x77, 0x4e, 0xc9, 0xdf, 0x89, 0xa4, 0x0f, 0x53, 0x7e, 0x55,
	0xbc, 0xe8, 0xee, 0x2d, 0x3f, 0x1a, 0x5e, 0x3f, 0x30, 0xbf, 0x17, 0x61, 0x70, 0xe7, 0x1f, 0x6a,
	0xae, 0xc6, 0x52, 0x89, 0xc1, 0x68, 0xc2, 0x94, 0xe0, 0x03, 0xbe, 0xd0, 0xd2, 0xc4, 0xd5, 0x7f,
	0x4d, 0xd4, 0x2a, 0x77, 0x6a, 0x64, 0x13, 0x4b, 0xb6, 0xb1, 0xe4, 0x26, 0x8b, 0xed, 0xee, 0xaf,
	0x9d, 0xaf, 0x9f, 0x0d, 0xd4, 0xaf, 0x64, 0x86, 0x6b, 0x27, 0xb8, 0x75, 0xf7, 0xdd, 0xa7, 0x65,
	0x82, 0xd1, 0x2a, 0xc1, 0xe8, 0x2b, 0xc1, 0xe8, 0x25, 0xc5, 0xde, 0x2a, 0xc5, 0xde, 0x7b, 0x8a,
	0x3d, 0xbf, 0x26, 0x61, 0x47, 0x79, 0x0f, 0xdd, 0x5f, 0x0a, 0x69, 0x27, 0xd1, 0x90, 0x8c, 0x60,
	0x46, 0x73, 0xe8, 0x5c, 0x42, 0x61, 0xa2, 0x8b, 0xfc, 0x8f, 0x6d, 0xac, 0x79, 0x38, 0x2c, 0xb9,
	0xbc, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x36, 0xdf, 0xd4, 0xda, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.PendingChangeExpiry, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PendingChangeExpiry):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.RoleAuthorizations) > 0 {
		for iNdEx := len(m.RoleAuthorizations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoleAuthorizations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RoleAuthorizations) > 0 {
		for _, e := range m.RoleAuthorizations {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.PendingChangeExpiry)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleAuthorizations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleAuthorizations = append(m.RoleAuthorizations, RoleAuthorization{})
			if err := m.RoleAuthorizations[len(m.RoleAuthorizations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingChangeExpiry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.PendingChangeExpiry, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
